# /// script
# requires-python = ">=3.11"
# dependencies = ["UnityPy>=1.20", "Pillow>=10.1", "numpy>=1.26"]
# ///
"""Build reference sprite sheets from an installed mod's textures into `assets/mods/`.

Same sheet format as build_assets.py (vanilla), for mods whose art style you want to match.
Mods ship plain PNGs, so nothing is extracted: point it at the mod folder and a regex.

    uv run build_mod_refs.py --name mo_storage --mod 3219596926 \\
        --regex 'Things/Building/Storage/' --note 'Medieval Overhaul storage'
    uv run build_mod_refs.py --list

`--mod` is a Workshop id (looked up under links/workshop), or a path to a mod folder. The regex
runs over each PNG's path relative to the mod root (forward slashes); masks are skipped unless
`--masks`. Writes `assets/mods/sheets/<name>_<n>.png`, `assets/mods/detail/<name>.png`, and
rewrites `assets/mods/INDEX.md` (+ `index.json`, `stats.json`) with every set built so far.

Like the vanilla sheets these are gitignored: other authors' art, study only — never copy,
trace or ship it.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import analyze
import build_assets as ba
import vanilla_tex as vt

OUT = vt.SKILL / "assets" / "mods"
REPO = vt.SKILL.parents[2]


def mod_root(mod: str) -> Path:
    p = Path(mod)
    if p.is_dir():
        return p
    ws = REPO / "links" / "workshop" / mod
    if ws.is_dir():
        return ws
    raise SystemExit(f"mod not found: {mod} (Workshop id under links/workshop, or a folder)")


def mod_name(root: Path) -> str:
    about = root / "About" / "About.xml"
    if about.exists():
        m = re.search(r"<name>(.*?)</name>", about.read_text(encoding="utf-8", errors="ignore"))
        if m:
            return m.group(1).strip()
    return root.name


def collect(root: Path, regex: str, masks: bool, cap: int) -> tuple[list[Path], int]:
    rx = re.compile(regex, re.IGNORECASE)
    mask = re.compile(ba.MASK, re.IGNORECASE)
    seen, hits = set(), []
    for fp in sorted(root.rglob("*.png")):
        rel = fp.relative_to(root).as_posix()
        if not rx.search(rel) or (not masks and mask.search(fp.stem)):
            continue
        # The same texture often ships once per version folder: keep the first copy.
        key = re.sub(r"^(\d\.\d|Common)/", "", rel)
        if key in seen:
            continue
        seen.add(key)
        hits.append(fp)
    total = len(hits)
    if total > cap:
        step = total / cap
        hits = [hits[int(i * step)] for i in range(cap)]
    return hits, total


def write_index(index: dict) -> None:
    lines = [
        "# Mod reference sheets — generated by build_mod_refs.py, do not edit",
        "",
        "Other mods' art for style matching (study only). Same layout as the vanilla sheets:",
        "`sheets/<name>_<n>.png` labelled at native size up to 128 px (`*` = scaled down),",
        "`detail/<name>.png` 4 sprites at 3x. Numbers in `index.json` / `stats.json`.",
        "",
    ]
    for name, e in index.items():
        sampled = f", sampled {e['shown']} of {e['total']}" if e["shown"] < e["total"] else ""
        lines.append(f"## {name}  ({e['shown']} sprites{sampled})")
        note = f" — {e['note']}" if e["note"] else ""
        lines.append(f"{e['mod']} (`{e['source']}`), `{e['regex']}`{note}")
        lines.append("")
        per = ba.COLS * ba.ROWS
        for i, sheet in enumerate(e["sheets"]):
            names = e["names"][i * per : (i + 1) * per]
            lines.append(f"- `{sheet}`: " + ", ".join(names))
        lines.append(f"- `detail/{name}.png`")
        s = e.get("stats") or {}
        if s:
            keys = [k for k in analyze.KEYS if k in s]
            lines.append("- median: " + ", ".join(f"{k} {s[k]['median']}" for k in keys))
        lines.append("")
    (OUT / "INDEX.md").write_text("\n".join(lines), encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawTextHelpFormatter)
    ap.add_argument("--name", help="set name, e.g. mo_storage (used in file names)")
    ap.add_argument("--mod", help="Workshop id or mod folder")
    ap.add_argument("--regex", default=r"Textures/", help="over the path relative to the mod root")
    ap.add_argument("--note", default="")
    ap.add_argument("--cap", type=int, default=96, help="max sprites (sampled evenly above it)")
    ap.add_argument("--masks", action="store_true", help="include _m / <dir>m mask textures")
    ap.add_argument("--list", action="store_true", help="list the sets built so far")
    a = ap.parse_args(argv)
    index_file = OUT / "index.json"
    index = json.loads(index_file.read_text()) if index_file.exists() else {}
    if a.list:
        for n, e in index.items():
            print(f"{n:20} {e['shown']:4} sprites  {e['mod']}  {e['regex']}")
        return 0
    if not (a.name and a.mod):
        ap.error("--name and --mod are required")
    root = mod_root(a.mod)
    files, total = collect(root, a.regex, a.masks, a.cap)
    if not files:
        print(f"{a.name}: no textures match {a.regex} under {root}", file=sys.stderr)
        return 1
    sheets, detail = OUT / "sheets", OUT / "detail"
    sheets.mkdir(parents=True, exist_ok=True)
    detail.mkdir(parents=True, exist_ok=True)
    for old in sheets.glob(f"{a.name}_*.png"):
        old.unlink()
    pages = ba.contact_sheets(a.name, files, sheets)
    ba.detail_sheet(files, detail / f"{a.name}.png")
    index[a.name] = {
        "mod": mod_name(root),
        "source": a.mod,
        "regex": a.regex,
        "note": a.note,
        "shown": len(files),
        "total": total,
        "sheets": [p.relative_to(OUT).as_posix() for p, _ in pages],
        "names": [n for _, ns in pages for n in ns],
        "stats": analyze.summarize([analyze.analyze(f) for f in files]),
    }
    index_file.write_text(json.dumps(index, indent=1))
    write_index(index)
    print(f"{a.name}: {len(files)}/{total} sprites, {len(pages)} sheet(s) -> {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
